Repository kikuyodev/kumi, pull requests merged in 2023-12, with the labels that each got.

#26 Initial editor screen
  Kumi.Game/Charts/Formats/ChartDecoder.cs
  Kumi.Game/Charts/WorkingChartCache.cs
  Kumi.Game/Gameplay/Drawables/DrawableDrumHit.cs
  Kumi.Game/Gameplay/Playfield.cs
  Kumi.Game/Graphics/Containers/InputBlockingContainer.cs
  Kumi.Game/Screens/Edit/EditorClock.cs
  Kumi.Game/Screens/Edit/EditorScreen.cs
  Kumi.Game/Screens/KumiScreenStack.cs
  Kumi.Game/Tests/KumiScreenTestScene.cs
  Kumi.Game/Tests/KumiTestScene.cs
  Kumi.Game/Tests/TestWorkingChart.cs
  Kumi.Tests/Visual/Edit/EditorScreenTestScene.cs
  Kumi.Tests/Visual/Gameplay/KumiPlayfieldTestScene.cs
  Kumi.Tests/Visual/Gameplay/PlayfieldTestScene.cs
Labels: area: editor, area: charts, size: l

#27 Editor bottom timeline (and overlay)
  Kumi.Game/Gameplay/Drawables/DrawableDrumHit.cs
  Kumi.Game/Graphics/UserInterface/KumiIconButton.cs
  Kumi.Game/Screens/Edit/EditorOverlay.cs
  Kumi.Game/Screens/Edit/EditorScreen.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/MarkerPart.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/TimelinePart.cs
  Kumi.Game/Screens/Edit/Timeline/PlaybackControl.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineBar.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineSummary.cs
Labels: area: editor, size: xl, area: charts

#30 Add more colours to the colours class
  Kumi.Game/Charts/BindableBeatDivisor.cs
  Kumi.Game/Charts/Objects/Note.cs
  Kumi.Game/Gameplay/Drawables/DrawableBigDrumHit.cs
  Kumi.Game/Gameplay/Drawables/DrawableDrumHit.cs
  Kumi.Game/Gameplay/KumiPlayfield.cs
  Kumi.Game/Graphics/Colors.cs
  Kumi.Game/Graphics/Colours.cs
  Kumi.Game/Graphics/UserInterface/KumiButton.cs
  Kumi.Game/Graphics/UserInterface/KumiCheckbox.cs
  Kumi.Game/Graphics/UserInterface/KumiIconButton.cs
  Kumi.Game/Graphics/UserInterface/KumiTabControl.cs
  Kumi.Game/Graphics/UserInterface/KumiTextBox.cs
  Kumi.Game/KumiGameBase.cs
  Kumi.Game/Overlays/Login/LoginPanel.cs
  Kumi.Game/Overlays/Login/LoginScreen.cs
  Kumi.Game/Overlays/Taskbar/TaskbarUserButton.cs
  Kumi.Game/Overlays/TaskbarOverlay.cs
  Kumi.Game/Screens/Edit/EditorOverlay.cs
  Kumi.Game/Screens/Edit/Menus/DrawableEditorBarMenuItem.cs
  Kumi.Game/Screens/Edit/Menus/EditorMenuBar.cs
  Kumi.Game/Screens/Edit/Timeline/BeatDivisorControl.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/MarkerPart.cs
  Kumi.Game/Screens/Edit/Timeline/PlaybackControl.cs
  Kumi.Game/Screens/Edit/Timeline/Timeline.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineArea.cs
  Kumi.Game/Screens/Edit/Timeline/TopBarTimeline.cs
  Kumi.Game/Screens/Select/ChartSetInfoWedge.cs
  Kumi.Game/Screens/Select/ChartSetInfoWedgeContent.cs
  Kumi.Game/Screens/Select/List/ChartListItem.cs
  Kumi.Game/Screens/Select/List/ChartSetListItem.cs
  Kumi.Tests/Visual/Gameplay/KumiPlayfieldTestScene.cs
  Kumi.Tests/Visual/Gameplay/PlayfieldTestScene.cs
  Kumi.sln.DotSettings
Labels: type: quality, size: l

#34 Score info (and temporary result screen)
  Kumi.Game/Charts/ChartImporter.cs
  Kumi.Game/Charts/ChartInfo.cs
  Kumi.Game/Charts/ChartManager.cs
  Kumi.Game/Charts/ChartMetadata.cs
  Kumi.Game/Charts/ChartSetInfo.cs
  Kumi.Game/Charts/Formats/ChartDecoder.cs
  Kumi.Game/Charts/IChartMetadata.cs
  Kumi.Game/Database/RealmAccess.cs
  Kumi.Game/Database/RealmObjectUtils.cs
  Kumi.Game/Gameplay/Judgements/Judgement.cs
  Kumi.Game/Gameplay/Playfield.cs
  Kumi.Game/Gameplay/Scoring/JudgementProcessor.cs
  Kumi.Game/Gameplay/Scoring/ScoreProcessor.cs
  Kumi.Game/Graphics/Sprites/AvatarSprite.cs
  Kumi.Game/KumiGameBase.cs
  Kumi.Game/Models/RealmAccount.cs
  Kumi.Game/Online/API/Accounts/APIAccount.cs
  Kumi.Game/Online/API/Accounts/IAccount.cs
  Kumi.Game/Scoring/IScoreInfo.cs
  Kumi.Game/Scoring/ScoreImporter.cs
  Kumi.Game/Scoring/ScoreInfo.cs
  Kumi.Game/Scoring/ScoreManager.cs
  Kumi.Game/Screens/Play/ChartLoaderDisplay.cs
  Kumi.Game/Screens/Play/Player.cs
  Kumi.Game/Screens/Play/ResultsScreen.cs
  Kumi.Tests/Charts/Formats/ChartEncoderTest.cs
  Kumi.Tests/TestResources.cs
Labels: size: xl, area: scoring

#35 Add a dynamic scroll algorithm
  Kumi.Game/Gameplay/Algorithms/DynamicScrollAlgorithm.cs
  Kumi.Game/Gameplay/KumiPlayfield.cs
  Kumi.Game/Gameplay/ScrollingNoteContainer.cs
Labels: area: gameplay, size: l

#36 Fix hit windows
  Kumi.Game/Charts/Objects/Windows/NoteWindows.cs
Labels: size: s

#37 Finish Score processing
  Kumi.Game/Extensions/NoteHitResultExtensions.cs
  Kumi.Game/Gameplay/Judgements/Judgement.cs
  Kumi.Game/Gameplay/Scoring/HealthGaugeProcessor.cs
  Kumi.Game/Gameplay/Scoring/JudgementProcessor.cs
  Kumi.Game/Gameplay/Scoring/ScoreProcessor.cs
  Kumi.Game/Kumi.Game.csproj
  Kumi.Game/KumiGameBase.cs
  Kumi.Game/Scoring/ScoreComboRank.cs
  Kumi.Game/Scoring/ScoreInfo.cs
  Kumi.Game/Scoring/ScoreRank.cs
  Kumi.Game/Screens/Play/Player.cs
Labels: size: l

#38 Add a more proper flow for the entire game
  Kumi.Game/Graphics/Backgrounds/BackgroundStack.cs
  Kumi.Game/KumiGame.cs
  Kumi.Game/Screens/KumiScreen.cs
  Kumi.Game/Screens/KumiScreenStack.cs
  Kumi.Game/Screens/LoaderScreen.cs
  Kumi.Game/Screens/Menu/MenuScreen.cs
  Kumi.Game/Screens/Select/ChartSetInfoWedgeContent.cs
  Kumi.Game/Screens/Select/List/ChartListItem.cs
  Kumi.Game/Screens/Select/SelectScreen.cs
Labels: size: l

#39 Show taskbar in-game
  Kumi.Game/Database/RealmAccess.cs
  Kumi.Game/Input/GlobalAction.cs
  Kumi.Game/Input/GlobalKeybindContainer.cs
  Kumi.Game/KumiGame.cs
  Kumi.Game/Overlays/TaskbarOverlay.cs
  Kumi.Game/Screens/Edit/Editor.cs
  Kumi.Game/Screens/KumiScreen.cs
  Kumi.Game/Screens/LoaderScreen.cs
  Kumi.Game/Screens/Menu/MenuScreen.cs
  Kumi.Game/Screens/Play/Player.cs
  Kumi.Game/Screens/Play/PlayerLoader.cs
Labels: size: l

#6 Create actual `APIConnection`
  Kumi.Game/Graphics/Sprites/AvatarSprite.cs
  Kumi.Game/KumiGameBase.cs
  Kumi.Game/Online/API/APIConnection.cs
  Kumi.Game/Online/API/APIError.cs
  Kumi.Game/Online/API/APIRequest.cs
  Kumi.Game/Online/API/APIRequestException.cs
  Kumi.Game/Online/API/APIResponse.cs
  Kumi.Game/Online/API/APIWebRequest.cs
  Kumi.Game/Online/API/Accounts/APIAccount.cs
  Kumi.Game/Online/API/Accounts/APICountry.cs
  Kumi.Game/Online/API/Accounts/APIGroup.cs
  Kumi.Game/Online/API/DummyAPIConnection.cs
  Kumi.Game/Online/API/IAPIConnectionProvider.cs
  Kumi.Game/Online/API/IHasStatus.cs
  Kumi.Game/Online/API/Requests/LoginRequest.cs
  Kumi.Game/Online/ProductionServerConfiguration.cs
  Kumi.Game/Overlays/Login/LoginScreen.cs
  Kumi.Game/Overlays/TaskbarOverlay.cs
Labels: area: online, type: api, size: l

#41 Health display HUD element
  Kumi.Game/Gameplay/Scoring/HealthGaugeProcessor.cs
  Kumi.Game/Gameplay/Scoring/JudgementProcessor.cs
  Kumi.Game/Screens/Play/HUD/Health/HealthBin.cs
  Kumi.Game/Screens/Play/HUD/HealthDisplay.cs
  Kumi.Game/Screens/Play/Player.cs
  Kumi.Tests/Visual/Play/HealthDisplayTestScene.cs
Labels: area: gameplay, size: l

#40 Fix duplicate keybinds
  Kumi.Game/Database/RealmBackedDefaultStore.cs
  Kumi.Game/Input/Bindings/KeybindStore.cs
  Kumi.Tests/Database/RealmBackedDefaultStoreTest.cs
Labels: size: xs

#42 Snap to nearest beat when dragging an object
  Kumi.Game/Charts/Formats/ChartDecoder.cs
  Kumi.Game/Charts/Timings/TimingPointHandler.cs
  Kumi.Game/Gameplay/KumiPlayfield.cs
  Kumi.Game/Screens/Edit/Blueprints/BlueprintContainer.cs
Labels: area: editor, size: m

#43 Editor History & Clipboard
  Kumi.Game/Charts/Formats/ChartEncoder.cs
  Kumi.Game/Extensions/NoteExtensions.cs
  Kumi.Game/IO/Formats/FileDecoder.cs
  Kumi.Game/IO/Formats/FileEncoder.cs
  Kumi.Game/Kumi.Game.csproj
  Kumi.Game/Screens/Edit/Blueprints/SelectionHandler.cs
  Kumi.Game/Screens/Edit/Compose/ComposeScreen.cs
  Kumi.Game/Screens/Edit/Editor.cs
  Kumi.Game/Screens/Edit/EditorChart.cs
  Kumi.Game/Screens/Edit/EditorChartPatcher.cs
  Kumi.Game/Screens/Edit/EditorHistoryHandler.cs
  Kumi.Game/Screens/Edit/EditorOverlay.cs
  Kumi.Game/Screens/Edit/EditorScreen.cs
  Kumi.Game/Screens/Edit/EditorScreenStack.cs
  Kumi.Tests/Editing/EditorChartPatcherTest.cs
Labels: size: xl

#45 Create development workflow
  Kumi.Desktop/App.config
  Kumi.Game/Kumi.Game.csproj
  Kumi.Game/KumiGameBase.cs
  Kumi.Game/Online/DevelopmentServerConfiguration.cs
  Kumi.Game/Online/ProductionServerConfiguration.cs
Labels: size: m

#44 Snap placement notes
  Kumi.Game/Screens/Edit/Compose/ComposeBlueprintContainer.cs
Labels: size: s

#46 Account registration overlay
  Kumi.Desktop/Kumi.Desktop.csproj
  Kumi.Game/Graphics/Containers/KumiFocusedOverlayContainer.cs
  Kumi.Game/Kumi.Game.csproj
  Kumi.Game/KumiGame.cs
  Kumi.Game/Online/API/APIConnection.cs
  Kumi.Game/Online/API/APIWebRequest.cs
  Kumi.Game/Online/API/DummyAPIConnection.cs
  Kumi.Game/Online/API/IAPIConnectionProvider.cs
  Kumi.Game/Online/API/Requests/RegisterRequest.cs
  Kumi.Game/Overlays/AccountRegistrationOverlay.cs
  Kumi.Game/Overlays/IOverlayManager.cs
  Kumi.Game/Overlays/Login/LoginPanel.cs
  Kumi.Game/Overlays/Login/LoginScreen.cs
  Kumi.Game/Overlays/Login/LoginScreenStack.cs
  Kumi.Game/Overlays/LoginOverlay.cs
  Kumi.Game/Overlays/TaskbarOverlay.cs
  Kumi.Game/Screens/Menu/MenuScreen.cs
  Kumi.Game/Tests/KumiScreenTestScene.cs
  Kumi.Game/Tests/KumiTestScene.cs
  Kumi.Resources/Kumi.Resources.csproj
  Kumi.Tests/Kumi.Tests.csproj
  Kumi.Tests/Online/TestDummyAPIConnection.cs
  Kumi.Tests/Online/TestDummyServerConnection.cs
  Kumi.Tests/Visual/Edit/EditorScreenTestScene.cs
  Kumi.Tests/Visual/Overlays/AccountRegistrationOverlayTestScene.cs
  Kumi.Tests/Visual/Play/PlayerTestScene.cs
  Kumi.sln
Labels: area: online, size: xl

#47 Add workflow for Websocket handling
  Kumi.Desktop/App.config
  Kumi.Game/Kumi.Game.csproj
  Kumi.Game/Online/API/APIConnection.cs
  Kumi.Game/Online/API/APIRequest.cs
  Kumi.Game/Online/API/APIResponse.cs
  Kumi.Game/Online/API/APIWebRequest.cs
  Kumi.Game/Online/API/Requests/LoginRequest.cs
  Kumi.Game/Online/API/Requests/Websocket/WebsocketTokenRequest.cs
  Kumi.Game/Online/DevelopmentServerConfiguration.cs
  Kumi.Game/Online/Server/IServerConnector.cs
  Kumi.Game/Online/Server/OpCode.cs
  Kumi.Game/Online/Server/Packet.cs
  Kumi.Game/Online/Server/Packets/Dispatch/NotificationDispatchPacket.cs
  Kumi.Game/Online/Server/Packets/DispatchPacket.cs
  Kumi.Game/Online/Server/Packets/HelloPacket.cs
  Kumi.Game/Online/Server/Packets/IdentifyPacket.cs
  Kumi.Game/Online/Server/Packets/PingPacket.cs
  Kumi.Game/Online/Server/Packets/PongPacket.cs
  Kumi.Game/Online/Server/ServerConnection.cs
  Kumi.Game/Online/Server/ServerConnector.cs
  Kumi.Game/Online/Server/ServerPacketOpCode.cs
  Kumi.Tests/Online/TestDummyServerConnection.cs
Labels: requires server changes, area: online, requires api changes, type: api, type: ws, size: l

#48 Add control overlay and notification section
  Kumi.Game/Input/GlobalAction.cs
  Kumi.Game/Input/GlobalKeybindContainer.cs
  Kumi.Game/KumiGame.cs
  Kumi.Game/Online/API/APIConnection.cs
  Kumi.Game/Online/DevelopmentServerConfiguration.cs
  Kumi.Game/Online/ProductionServerConfiguration.cs
  Kumi.Game/Online/Server/IServerConnector.cs
  Kumi.Game/Online/Server/Packet.cs
  Kumi.Game/Online/Server/Packets/Dispatch/NotificationDispatchPacket.cs
  Kumi.Game/Online/Server/Packets/DispatchPacket.cs
  Kumi.Game/Online/Server/ServerConnector.cs
  Kumi.Game/Overlays/Control/BasicNotification.cs
  Kumi.Game/Overlays/Control/Notification.cs
  Kumi.Game/Overlays/Control/NotificationSection.cs
  Kumi.Game/Overlays/ControlOverlay.cs
  Kumi.Game/Overlays/INotificationManager.cs
  Kumi.Game/Overlays/Taskbar/TaskbarButton.cs
  Kumi.Game/Overlays/Taskbar/TaskbarNotificationButton.cs
  Kumi.Game/Overlays/TaskbarOverlay.cs
  Kumi.Tests/Visual/UserInterface/AccountRegistrationOverlayTestScene.cs
  Kumi.Tests/Visual/UserInterface/ControlOverlayTestScene.cs
  Kumi.Tests/Visual/UserInterface/TaskbarTestScene.cs
  Kumi.sln.DotSettings
Labels: size: xl

#50 Restructure component loading
  Kumi.Game/KumiGame.cs
  Kumi.Game/Overlays/TaskbarOverlay.cs
  Kumi.Game/Screens/Select/ChartSetInfoWedgeContent.cs
  Kumi.Game/Screens/Select/List/ListSelect.cs
  Kumi.Game/Screens/Select/SelectScreen.cs
Labels: size: l

#52 Add the ability to drag and drop imports into the game
  Kumi.Game/KumiGame.cs
  Kumi.Game/KumiGameBase.cs
Labels: type: behavioural, area: input/output, size: m

#54 Fix subscriptions not running
  Kumi.Game/Database/RealmAccess.cs
  Kumi.Game/Input/Bindings/RealmBackedKeyBindingContainer.cs
  Kumi.Game/KumiGameBase.cs
  Kumi.Game/Tests/RealmTestGame.cs
Labels: type: api, type: behavioural, area: input/output, area: database, size: m

#55 Add menu buttons
  Kumi.Game/Graphics/Containers/KumiFocusedOverlayContainer.cs
  Kumi.Game/KumiGame.cs
  Kumi.Game/Overlays/IOverlayManager.cs
  Kumi.Game/Overlays/MusicController.cs
  Kumi.Game/Overlays/OverlayActivation.cs
  Kumi.Game/Overlays/TaskbarOverlay.cs
  Kumi.Game/Screens/Edit/Editor.cs
  Kumi.Game/Screens/KumiScreen.cs
  Kumi.Game/Screens/LoaderScreen.cs
  Kumi.Game/Screens/Menu/MenuButton.cs
  Kumi.Game/Screens/Menu/MenuButtons.cs
  Kumi.Game/Screens/Menu/MenuMusicOverlay.cs
  Kumi.Game/Screens/Menu/MenuScreen.cs
  Kumi.Game/Screens/Play/Player.cs
  Kumi.Game/Screens/Play/PlayerLoader.cs
  Kumi.Game/Screens/Select/SelectScreen.cs
  Kumi.Game/Tests/KumiScreenTestScene.cs
Labels: zone: main menu, size: xl

#53 Finish control center
  Kumi.Game/Overlays/Control/ConnectionSection.cs
  Kumi.Game/Overlays/Control/MusicControlSection.cs
  Kumi.Game/Overlays/Control/MusicProgressBar.cs
  Kumi.Game/Overlays/Control/NotificationSection.cs
  Kumi.Game/Overlays/ControlOverlay.cs
  Kumi.Game/Overlays/MusicController.cs
Labels: size: xl, area: overlays

#57 Add drawable balloons and drum rolls
  Kumi.Game/Charts/Objects/Note.cs
  Kumi.Game/Gameplay/Algorithms/DynamicScrollAlgorithm.cs
  Kumi.Game/Gameplay/Algorithms/IScrollAlgorithm.cs
  Kumi.Game/Gameplay/Algorithms/LinearScrollAlgorithm.cs
  Kumi.Game/Gameplay/Drawables/DrawableBalloon.cs
  Kumi.Game/Gameplay/Drawables/DrawableBigDrumHit.cs
  Kumi.Game/Gameplay/Drawables/DrawableDrumRoll.cs
  Kumi.Game/Gameplay/Drawables/DrawableNote.cs
  Kumi.Game/Gameplay/Drawables/Parts/YellowCirclePart.cs
  Kumi.Game/Gameplay/Judgements/Judgement.cs
  Kumi.Game/Gameplay/KumiPlayfield.cs
  Kumi.Game/Gameplay/Scoring/HealthGaugeProcessor.cs
  Kumi.Game/Gameplay/Scoring/JudgementProcessor.cs
  Kumi.Game/Gameplay/Scoring/ScoreProcessor.cs
  Kumi.Game/Gameplay/ScrollingNoteContainer.cs
Labels: type: behavioural, size: xl, area: charts

#56 Log errors to notifications (and prevent from hard-crashing on release)
  Kumi.Game/KumiGame.cs
  Kumi.Game/KumiGameBase.cs
  Kumi.Game/Online/API/APIConnection.cs
  Kumi.Game/Online/API/APIRequest.cs
  Kumi.Game/Overlays/Login/LoginScreen.cs
Labels: size: m

#58 Add bar lines to playfield
  Kumi.Game/Charts/Objects/BarLine.cs
  Kumi.Game/Gameplay/BarLineGenerator.cs
  Kumi.Game/Gameplay/Drawables/DrawableBarLine.cs
  Kumi.Game/Gameplay/Drawables/DrawableNote.cs
  Kumi.Game/Gameplay/Judgements/BarLineJudgement.cs
  Kumi.Game/Gameplay/Judgements/Judgement.cs
  Kumi.Game/Gameplay/KumiPlayfield.cs
  Kumi.Game/Gameplay/Scoring/JudgementProcessor.cs
Labels: size: l

#63 Fix end time not being offset when dragged
  Kumi.Game/Screens/Edit/Blueprints/BlueprintContainer.cs
Labels: size: xs

#61 Timeline touchup
  Kumi.Game/Screens/Edit/Blueprints/BlueprintContainer.cs
  Kumi.Game/Screens/Edit/Blueprints/EditorBlueprintContainer.cs
  Kumi.Game/Screens/Edit/Blueprints/SelectionHandler.cs
  Kumi.Game/Screens/Edit/Compose/ComposeScreen.cs
  Kumi.Game/Screens/Edit/EditorChart.cs
  Kumi.Game/Screens/Edit/EditorOverlay.cs
  Kumi.Game/Screens/Edit/EditorScreenWithTimeline.cs
  Kumi.Game/Screens/Edit/Timeline/BottomBarTimeline.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/DrawableTimingPoint.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/MarkerPart.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/PreviewTimePart.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/TimelinePart.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/TimingPointsPart.cs
  Kumi.Game/Screens/Edit/Timeline/Timeline.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineArea.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineBlueprintContainer.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineNoteBlueprint.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineSelectionHandler.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineSummary.cs
Labels: area: editor, type: behavioural, size: xl

#60 Implement saving for editor
  Kumi.Game/Charts/ChartImporter.cs
  Kumi.Game/Charts/ChartManager.cs
  Kumi.Game/Database/RealmObjectUtils.cs
  Kumi.Game/Screens/Edit/Editor.cs
  Kumi.Game/Screens/Edit/EditorChart.cs
  Kumi.Game/Utils/StringUtils.cs
Labels: area: editor, size: l

#64 Fix incorrect anchor with drum rolls
  Kumi.Game/Gameplay/Drawables/DrawableDrumRoll.cs
  Kumi.Game/Screens/Edit/Compose/Selection/DrumRollSelectionBlueprint.cs
Labels: size: s

#65 Editor setup screen
  Kumi.Game/Charts/MetadataUtils.cs
  Kumi.Game/Graphics/UserInterface/KumiFileSelector.cs
  Kumi.Game/Graphics/UserInterface/KumiPopover.cs
  Kumi.Game/KumiGame.cs
  Kumi.Game/KumiGameBase.cs
  Kumi.Game/Overlays/MusicController.cs
  Kumi.Game/Screens/Edit/Components/EditorSliderBar.cs
  Kumi.Game/Screens/Edit/Editor.cs
  Kumi.Game/Screens/Edit/EditorOverlay.cs
  Kumi.Game/Screens/Edit/EditorScreen.cs
  Kumi.Game/Screens/Edit/EditorScreenWithTimeline.cs
  Kumi.Game/Screens/Edit/Setup/FileChooser.cs
  Kumi.Game/Screens/Edit/Setup/RomanisedTextBox.cs
  Kumi.Game/Screens/Edit/Setup/Sections/ChartSection.cs
  Kumi.Game/Screens/Edit/Setup/Sections/MetadataSection.cs
  Kumi.Game/Screens/Edit/Setup/Sections/ResourcesSection.cs
  Kumi.Game/Screens/Edit/Setup/Sections/SetupSection.cs
  Kumi.Game/Screens/Edit/Setup/SetupScreen.cs
  Kumi.Game/Screens/Edit/Setup/TextBoxWithPopover.cs
  Kumi.Game/Screens/Edit/Timeline/BottomBarTimeline.cs
  Kumi.Tests/Visual/Edit/EditorSliderBarTestScene.cs
Labels: size: xxl

#66 Editor timing screen
  Kumi.Game/Bindables/LazyBindable.cs
  Kumi.Game/Charts/ChartManager.cs
  Kumi.Game/Charts/Formats/ChartDecoder.cs
  Kumi.Game/Charts/Formats/ChartEncoder.cs
  Kumi.Game/Charts/Objects/BarLine.cs
  Kumi.Game/Charts/Objects/INote.cs
  Kumi.Game/Charts/Objects/Note.cs
  Kumi.Game/Charts/Timings/TimingPoint.cs
  Kumi.Game/Charts/Timings/UninheritedTimingPoint.cs
  Kumi.Game/Graphics/UserInterface/KumiButton.cs
  Kumi.Game/Graphics/UserInterface/KumiTextBox.cs
  Kumi.Game/Screens/Edit/Compose/ComposeScreen.cs
  Kumi.Game/Screens/Edit/Editor.cs
  Kumi.Game/Screens/Edit/EditorHistoryHandler.cs
  Kumi.Game/Screens/Edit/EditorOverlay.cs
  Kumi.Game/Screens/Edit/EditorScreenWithTimeline.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/DrawableTick.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/TimelineTimingPoint.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/TimingPointPiece.cs
  Kumi.Game/Screens/Edit/Timeline/Timeline.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineBlueprintContainer.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineTickDisplay.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineTimingPointDisplay.cs
  Kumi.Game/Screens/Edit/Timing/Configuration/BPMTextBox.cs
  Kumi.Game/Screens/Edit/Timing/Configuration/ConfigurationSection.cs
  Kumi.Game/Screens/Edit/Timing/Configuration/ScrollSpeedSection.cs
  Kumi.Game/Screens/Edit/Timing/Configuration/StartTimeSection.cs
  Kumi.Game/Screens/Edit/Timing/Configuration/TimeSignatureTextBox.cs
  Kumi.Game/Screens/Edit/Timing/Configuration/UninheritedSection.cs
  Kumi.Game/Screens/Edit/Timing/Configuration/VolumeSection.cs
  Kumi.Game/Screens/Edit/Timing/DrawableTimingPoint.cs
  Kumi.Game/Screens/Edit/Timing/SummarySliderBar.cs
  Kumi.Game/Screens/Edit/Timing/TimingPointConfiguration.cs
  Kumi.Game/Screens/Edit/Timing/TimingPointFlowList.cs
  Kumi.Game/Screens/Edit/Timing/TimingPointList.cs
  Kumi.Game/Screens/Edit/Timing/TimingPointSummary.cs
  Kumi.Game/Screens/Edit/Timing/TimingScreen.cs
  Kumi.Tests/Visual/Gameplay/PlayfieldTestScene.cs
  Kumi.sln.DotSettings
Labels: area: editor, size: xxl

#68 Add simple context menu
  Kumi.Game/Screens/Select/List/ChartListItem.cs
  Kumi.Game/Screens/Select/List/ChartSetListItem.cs
  Kumi.Game/Screens/Select/List/ListSelect.cs
  Kumi.Game/Screens/Select/SelectScreen.cs
  Kumi.Tests/Editing/EditorChartPatcherTest.cs
Labels: size: l

#67 Timing screen touchups
  Kumi.Game/Graphics/Containers/AlwaysLastFillFlowContainer.cs
  Kumi.Game/Screens/Edit/EditorHistoryHandler.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineTickDisplay.cs
  Kumi.Game/Screens/Edit/Timing/Configuration/StartTimeSection.cs
  Kumi.Game/Screens/Edit/Timing/TimingPointFlowList.cs
  Kumi.Game/Screens/Edit/Timing/TimingPointList.cs
Labels: size: l

#69 Editor select screen
  Kumi.Game/Graphics/Containers/AlwaysLastFillFlowContainer.cs
  Kumi.Game/Screens/Menu/MenuScreen.cs
  Kumi.Game/Screens/Select/EditSelectScreen.cs
  Kumi.Game/Screens/Select/EditWedge.cs
  Kumi.Game/Screens/Select/PlaySelectScreen.cs
  Kumi.Game/Screens/Select/SelectScreen.cs
Labels: size: l

#71 Setting overlay
  Kumi.Game/Graphics/UserInterface/KumiDropdown.cs
  Kumi.Game/Graphics/UserInterface/KumiPasswordTextBox.cs
  Kumi.Game/Graphics/UserInterface/KumiSliderBar.cs
  Kumi.Game/Graphics/UserInterface/KumiTabControl.cs
  Kumi.Game/Input/GlobalAction.cs
  Kumi.Game/Input/GlobalKeybindContainer.cs
  Kumi.Game/Kumi.Game.csproj
  Kumi.Game/KumiGame.cs
  Kumi.Game/Overlays/SettingOverlay.cs
  Kumi.Game/Overlays/Settings/Audio/VolumeSection.cs
  Kumi.Game/Overlays/Settings/AudioSettings.cs
  Kumi.Game/Overlays/Settings/Components/CheckboxComponent.cs
  Kumi.Game/Overlays/Settings/Components/CheckboxSettingItem.cs
  Kumi.Game/Overlays/Settings/Components/DropdownComponent.cs
  Kumi.Game/Overlays/Settings/Components/DropdownEnumSettingItem.cs
  Kumi.Game/Overlays/Settings/Components/DropdownSettingItem.cs
  Kumi.Game/Overlays/Settings/Components/LabelledSettingItem.cs
  Kumi.Game/Overlays/Settings/Components/SliderBarComponent.cs
  Kumi.Game/Overlays/Settings/Components/SliderBarSettingItem.cs
  Kumi.Game/Overlays/Settings/Components/TextBoxComponent.cs
  Kumi.Game/Overlays/Settings/Components/TextBoxSettingItem.cs
  Kumi.Game/Overlays/Settings/Graphics/LayoutSection.cs
  Kumi.Game/Overlays/Settings/Graphics/RendererSettings.cs
  Kumi.Game/Overlays/Settings/GraphicsSettings.cs
  Kumi.Game/Overlays/Settings/SettingScreen.cs
  Kumi.Game/Overlays/Settings/SettingSection.cs
  Kumi.Game/Overlays/Taskbar/TaskbarSettingButton.cs
  Kumi.Game/Overlays/TaskbarOverlay.cs
  Kumi.Tests/Visual/UserInterface/SettingOverlayTestScene.cs
Labels: size: xxl, area: overlays

#70 Create chat channel packets
  Kumi.Game/Online/API/Chat/APIChatChannel.cs
  Kumi.Game/Online/API/Chat/APIChatMessage.cs
  Kumi.Game/Online/Server/Packets/Dispatch/ChatChannelAddEvent.cs
  Kumi.Game/Online/Server/Packets/Dispatch/ChatMessageEvent.cs
Labels: size: m

#72 Adjust certain desktop things
  Kumi.Desktop/Program.cs
  Kumi.Game/KumiGame.cs
Labels: platform: windows, type: behavioural, area: input/output, size: m

#73 Small initial release fixes
  Kumi.Game/Gameplay/Drawables/DrawableBarLine.cs
  Kumi.Game/Gameplay/KumiPlayfield.cs
  Kumi.Game/Gameplay/ScrollingNoteContainer.cs
  Kumi.Game/Screens/Edit/Blueprints/BlueprintContainer.cs
  Kumi.Game/Screens/Edit/Blueprints/EditorBlueprintContainer.cs
  Kumi.Game/Screens/Edit/Blueprints/SelectionHandler.cs
  Kumi.Game/Screens/Edit/Compose/ComposeScreen.cs
  Kumi.Game/Screens/Edit/Compose/NoteComposer.cs
  Kumi.Game/Screens/Edit/Compose/Placement/SpanPlacementBlueprint.cs
  Kumi.Game/Screens/Edit/Editor.cs
  Kumi.Game/Screens/Edit/EditorScreenWithTimeline.cs
  Kumi.Game/Screens/Edit/ISnapProvider.cs
  Kumi.Game/Screens/Edit/Setup/Sections/ResourcesSection.cs
  Kumi.Game/Screens/Edit/Timeline/BeatDivisorControl.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/DrawableTick.cs
  Kumi.Game/Screens/Edit/Timeline/Parts/TimingPointPiece.cs
  Kumi.Game/Screens/Edit/Timeline/Timeline.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineBlueprintContainer.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineNoteBlueprint.cs
  Kumi.Game/Screens/Edit/Timeline/TimelineTickDisplay.cs
  Kumi.Game/Screens/Edit/Timing/TimingPointConfiguration.cs
  Kumi.Game/Screens/Edit/Timing/TimingPointFlowList.cs
  Kumi.Game/Screens/Select/SelectScreen.cs
Labels: size: l

#74 Add activities and a discord RPC
  Kumi.Desktop/DiscordPresence.cs
  Kumi.Desktop/Kumi.Desktop.csproj
  Kumi.Desktop/KumiDesktopGame.cs
  Kumi.Desktop/Program.cs
  Kumi.Game/KumiGameBase.cs
  Kumi.Game/Online/Activity.cs
  Kumi.Game/Online/PlayerActivity.cs
  Kumi.Game/Screens/KumiScreen.cs
  Kumi.Game/Screens/Menu/MenuScreen.cs
Labels: size: l

#76 Add option to export from editor
  Kumi.Game/Charts/ChartManager.cs
  Kumi.Game/Charts/Events/SetMediaEvent.cs
  Kumi.Game/Database/IModelExporter.cs
  Kumi.Game/Database/ModelExporter.cs
  Kumi.Game/Gameplay/Drawables/DrawableBarLine.cs
  Kumi.Game/KumiGameBase.cs
  Kumi.Game/Screens/Edit/Editor.cs
  Kumi.Game/Screens/Edit/EditorOverlay.cs
Labels: size: m

#77 Fix `DrumHitPartTestScene` regression
  Kumi.Tests/Visual/Gameplay/DrumHitPartTestScene.cs
Labels: area: gameplay, type: testing, size: s

#79 Add the rest of notes to `Note.ToSaveableString()`
  Kumi.Game/Extensions/NoteExtensions.cs
Labels: size: xs

#81 Fix subscriptions, again
  Kumi.Game/Database/RealmAccess.cs
Labels: size: s

#80 Primatively create Mods
  Kumi.Game/Gameplay/Mods/Mod.cs
  Kumi.Game/Gameplay/Mods/ModDoubleTime.cs
  Kumi.Game/Gameplay/Scoring/HealthGaugeProcessor.cs
  Kumi.Game/Gameplay/Scoring/JudgementProcessor.cs
  Kumi.Game/Gameplay/Scoring/ScoreProcessor.cs
  Kumi.Game/Overlays/Select/ModSelectionOverlay.cs
  Kumi.Game/Screens/Play/Player.cs
  Kumi.Game/Screens/Select/PlaySelectScreen.cs
  Kumi.Tests/Visual/Play/PlayerTestScene.cs
Labels: area: mods, area: gameplay, type: behavioural, size: l

#82 Naively add chart subscriptions
  Kumi.Game/Screens/Select/List/ListSelect.cs
  Kumi.Game/Screens/Select/SelectScreen.cs
Labels: size: m

#78 Create progress notification
  Kumi.Game/Overlays/Control/Notification.cs
  Kumi.Game/Overlays/Control/ProgressNotification.cs
  Kumi.Game/Screens/Edit/Compose/ComposeScreen.cs
  Kumi.Tests/Visual/UserInterface/ControlOverlayTestScene.cs
Labels: type: behavioural, size: l, area: overlays

#83 Make cached mods a bindable list
  Kumi.Game/Gameplay/Mods/Mod.cs
  Kumi.Game/Gameplay/Mods/ModDoubleTime.cs
  Kumi.Game/Gameplay/Scoring/HealthGaugeProcessor.cs
  Kumi.Game/Gameplay/Scoring/JudgementProcessor.cs
  Kumi.Game/Gameplay/Scoring/ScoreProcessor.cs
  Kumi.Game/KumiGame.cs
  Kumi.Game/KumiGameBase.cs
  Kumi.Game/Overlays/Select/ModSelectionOverlay.cs
  Kumi.Game/Screens/Play/Player.cs
  Kumi.Tests/Visual/Play/PlayerTestScene.cs
Labels: area: mods, size: l

#84 Mod selector overlay (and selected mods indicator)
  Kumi.Game/Gameplay/Mods/Mod.cs
  Kumi.Game/Gameplay/Mods/ModDoubleTime.cs
  Kumi.Game/Gameplay/Mods/ModHalfTime.cs
  Kumi.Game/Input/GlobalAction.cs
  Kumi.Game/Input/GlobalKeybindContainer.cs
  Kumi.Game/KumiGame.cs
  Kumi.Game/Overlays/Select/ModSelectionOverlay.cs
  Kumi.Game/Screens/Edit/Editor.cs
  Kumi.Game/Screens/Select/EditSelectScreen.cs
  Kumi.Game/Screens/Select/ModSelectButton.cs
  Kumi.Game/Screens/Select/Mods/DrawableModSelector.cs
  Kumi.Game/Screens/Select/Mods/ModIndicator.cs
  Kumi.Game/Screens/Select/Mods/ModSelectionOverlay.cs
  Kumi.Game/Screens/Select/Mods/ModSelectorList.cs
  Kumi.Game/Screens/Select/Mods/SelectedModsIndicator.cs
  Kumi.Game/Screens/Select/PlaySelectScreen.cs
  Kumi.Game/Screens/Select/SelectScreen.cs
Labels: size: xl

#85 Chart upload flow
  Kumi.Desktop/Program.cs
  Kumi.Game/Charts/ChartInfo.cs
  Kumi.Game/Charts/ChartManager.cs
  Kumi.Game/Charts/ChartSetInfo.cs
  Kumi.Game/Database/IModelExporter.cs
  Kumi.Game/Database/ModelExporter.cs
  Kumi.Game/Database/RealmAccess.cs
  Kumi.Game/Online/API/APIResponse.cs
  Kumi.Game/Online/API/Requests/Responses/APIChartSet.cs
  Kumi.Game/Online/API/Requests/Responses/UploadedChartResponse.cs
  Kumi.Game/Online/API/Requests/UploadChartSetRequest.cs
  Kumi.Game/Overlays/Settings/Components/CheckboxComponent.cs
  Kumi.Game/Overlays/Settings/Components/LabelledSettingItem.cs
  Kumi.Game/Screens/Edit/Editor.cs
  Kumi.Game/Screens/Edit/EditorOverlay.cs
  Kumi.Game/Screens/Edit/Popup/EditorPopup.cs
  Kumi.Game/Screens/Edit/Popup/ExitWithoutSavingPopup.cs
  Kumi.Game/Screens/Edit/Popup/UploadPopup.cs
  Kumi.sln.DotSettings
Labels: area: online, area: charts, size: l

#87 README
  LICENSE
  README.md
Labels: size: m

#88 Finish results screen
  Kumi.Game/Database/RealmAccess.cs
  Kumi.Game/Database/RealmObjectUtils.cs
  Kumi.Game/Gameplay/Scoring/HealthGaugeProcessor.cs
  Kumi.Game/Gameplay/Scoring/ScoreProcessor.cs
  Kumi.Game/Scoring/ScoreComboRank.cs
  Kumi.Game/Scoring/ScoreInfo.cs
  Kumi.Game/Scoring/ScoreRank.cs
  Kumi.Game/Scoring/ScoreStatistics.cs
  Kumi.Game/Screens/Play/ChartLoaderDisplay.cs
  Kumi.Game/Screens/Play/DrawableChartInfo.cs
  Kumi.Game/Screens/Play/Player.cs
  Kumi.Game/Screens/Play/ResultsScreen.cs
  Kumi.Tests/TestResources.cs
  Kumi.Tests/Visual/Play/ResultsScreenTestScene.cs
  Kumi.sln.DotSettings
Labels: zone: results, size: xl, area: screens

#89 Select all hotkey for compose screen
  Kumi.Game/Screens/Edit/Compose/ComposeScreen.cs
Labels: size: s

#90 Store online id in chart file
  Kumi.Game/Charts/Formats/ChartDecoder.cs
  Kumi.Game/Charts/Formats/ChartEncoder.cs
Labels: size: s

#91 Add drum samples
  Kumi.Game/Audio/DrawablePausableSample.cs
  Kumi.Game/Audio/ISamplePausablePlayback.cs
  Kumi.Game/Gameplay/Drawables/DrawableBigDrumHit.cs
  Kumi.Game/Gameplay/Drawables/DrawableDrumHit.cs
  Kumi.Game/Gameplay/Drawables/DrawableNote.cs
  Kumi.Game/Gameplay/KumiPlayfield.cs
  Kumi.Game/Gameplay/Playfield.cs
  Kumi.Game/Screens/Edit/Compose/ComposeScreen.cs
  Kumi.Game/Screens/Edit/Editor.cs
  Kumi.Game/Screens/Edit/EditorChart.cs
  Kumi.Game/Screens/Edit/EditorClock.cs
  Kumi.Game/Screens/Play/Player.cs
  Kumi.Resources/Audio/.gitkeep
  Kumi.Resources/Kumi.Resources.csproj
  Kumi.Resources/Samples/gameplay/drum-rim.wav
  Kumi.Resources/Samples/gameplay/drum.wav
  Kumi.sln.DotSettings
Labels: size: l, type: audio

#92 Add overlap scroll algorithm
  Kumi.Game/Gameplay/Algorithms/DynamicScrollAlgorithm.cs
  Kumi.Game/Gameplay/Algorithms/OverlapScrollAlgorithm.cs
  Kumi.Game/Gameplay/KumiPlayfield.cs
Labels: size: m

#93 Fix null height for buttons in timing point flow list
  Kumi.Game/Screens/Edit/Timing/TimingPointFlowList.cs
Labels: size: xs

#94 Add custom scroll container
  Kumi.Game/Graphics/Containers/KumiScrollContainer.cs
  Kumi.Game/Graphics/Containers/ZoomableScrollContainer.cs
  Kumi.Game/Graphics/UserInterface/KumiDropdown.cs
  Kumi.Game/Graphics/UserInterface/KumiFileSelector.cs
  Kumi.Game/Overlays/Chat/ChannelListing.cs
  Kumi.Game/Overlays/Chat/ChannelPickerPopover.cs
  Kumi.Game/Overlays/Chat/ChannelScrollContainer.cs
  Kumi.Game/Overlays/ControlOverlay.cs
  Kumi.Game/Overlays/SettingOverlay.cs
  Kumi.Game/Screens/Edit/Menus/EditorMenuBar.cs
  Kumi.Game/Screens/Edit/Timing/TimingPointList.cs
  Kumi.Game/Screens/Select/List/ListSelect.cs
  Kumi.Game/Screens/Select/Mods/ModSelectionOverlay.cs
  Kumi.Game/Screens/Select/SelectScreen.cs
Labels: size: l

#95 Create context menu
  Kumi.Game/Graphics/Containers/KumiContextMenuContainer.cs
  Kumi.Game/Graphics/Menus/KumiMenu.cs
  Kumi.Game/Screens/Edit/Menus/DrawableEditorBarMenuItem.cs
  Kumi.Game/Screens/Edit/Menus/EditorMenuBar.cs
  Kumi.Game/Screens/Select/SelectScreen.cs
Labels: size: m
